---
name: "Vibrant API"
slug: "vbt-api"
version: "1.0.0"
description: "Vibrant's API for mobile app usage."
startup: services
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
image: harbor-dev.vibrantbt.net/gateway/api:latest
map:
  - data:rw
options:
  db_uri: "!secret vbt_db_uri"
  db_schema: "public"
  db_anon_role: "web_anon"
  jwt_secret: "!secret vbt_api_jwt_secret"
  port: 3000
schema:
  db_uri: str
  db_schema: str
  db_anon_role: str
  jwt_secret: str
  port: int
ports:
  "3000/tcp": 3000
ports_description:
  "3000/tcp": "Vibrant API HTTP"
